from typing import Dict, List, Literal, Optional, Tuple, TypeAlias

Headers = Dict[str, List[str]]
SymmetricAlgorithmName: TypeAlias = Literal["aes128", "aes192", "aes256"]
AeadAlgorithmName: TypeAlias = Literal["eax", "ocb", "gcm"]
CompressionAlgorithmName: TypeAlias = Literal["zip", "zlib", "bzip2"]
EncryptionVersionName: TypeAlias = Literal["seipd-v1", "seipd-v2"]

class PublicKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[PublicKey, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> PublicKey: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def user_ids(self) -> List[str]: ...
    def verify_bindings(self) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class SecretKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[SecretKey, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> SecretKey: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def secret_subkey_count(self) -> int: ...
    @property
    def user_ids(self) -> List[str]: ...
    def verify_bindings(self) -> None: ...
    def to_public_key(self) -> PublicKey: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class SignatureInfo:
    @property
    def version(self) -> int: ...
    @property
    def signature_type(self) -> Optional[str]: ...
    @property
    def hash_algorithm(self) -> Optional[str]: ...
    @property
    def public_key_algorithm(self) -> Optional[str]: ...
    @property
    def issuer_key_ids(self) -> List[str]: ...
    @property
    def issuer_fingerprints(self) -> List[str]: ...
    @property
    def creation_time(self) -> Optional[int]: ...
    @property
    def signature_expiration_seconds(self) -> Optional[int]: ...
    @property
    def signer_user_id(self) -> Optional[str]: ...
    @property
    def signed_hash_value(self) -> Optional[bytes]: ...
    @property
    def salt(self) -> Optional[bytes]: ...
    @property
    def is_one_pass(self) -> bool: ...

class Message:
    @staticmethod
    def from_armor(data: str) -> Tuple[Message, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> Message: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def headers(self) -> Optional[Headers]: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def payload_bytes(self) -> bytes: ...
    def payload_text(self) -> str: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...
    def signature_count(self) -> int: ...
    def one_pass_signature_count(self) -> int: ...
    def regular_signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def verify_signature(self, key: PublicKey, index: int = 0) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: int = 0) -> None: ...
    def decrypt(
        self, key: SecretKey, password: Optional[str] = None
    ) -> DecryptedMessage: ...
    def decrypt_with_password(self, password: str) -> DecryptedMessage: ...

class DecryptedMessage:
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def payload_bytes(self) -> bytes: ...
    def payload_text(self) -> str: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...

class DetachedSignature:
    @staticmethod
    def from_armor(data: str) -> Tuple[DetachedSignature, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> DetachedSignature: ...
    @staticmethod
    def sign_binary(
        data: bytes, key: SecretKey, password: Optional[str] = None
    ) -> DetachedSignature: ...
    def signature_info(self) -> SignatureInfo: ...
    def verify(self, key: PublicKey, data: bytes) -> None: ...
    def verify_signature(self, key: PublicKey, data: bytes) -> SignatureInfo: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class CleartextSignedMessage:
    @staticmethod
    def from_armor(data: str) -> Tuple[CleartextSignedMessage, Headers]: ...
    @staticmethod
    def sign(
        text: str, key: SecretKey, password: Optional[str] = None
    ) -> CleartextSignedMessage: ...
    @property
    def text(self) -> str: ...
    def signed_text(self) -> str: ...
    def signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def verify_signature(
        self, key: PublicKey, index: Optional[int] = None
    ) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: Optional[int] = None) -> None: ...
    def to_armored(self) -> str: ...

class MessageInfo:
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def headers(self) -> Optional[Headers]: ...

def inspect_message(data: str) -> MessageInfo: ...
def inspect_message_bytes(data: bytes) -> MessageInfo: ...
def sign_message(
    data: bytes, signer: SecretKey, password: Optional[str] = None, file_name: str = ""
) -> str: ...
def sign_cleartext_message(
    text: str, signer: SecretKey, password: Optional[str] = None
) -> str: ...
def encrypt_message_to_recipient(
    data: bytes,
    recipient: PublicKey,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
) -> str: ...
def encrypt_message_with_password(
    data: bytes,
    password: str,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
) -> str: ...
