from typing import Dict, List, Literal, Optional, Tuple, TypeAlias

Headers = Dict[str, List[str]]
SymmetricAlgorithmName: TypeAlias = Literal["aes128", "aes192", "aes256"]
AeadAlgorithmName: TypeAlias = Literal["eax", "ocb", "gcm"]
CompressionAlgorithmName: TypeAlias = Literal["zip", "zlib", "bzip2"]
EncryptionVersionName: TypeAlias = Literal["seipd-v1", "seipd-v2"]
HashAlgorithmName: TypeAlias = Literal[
    "sha1", "sha224", "sha256", "sha384", "sha512", "sha3-256", "sha3-512"
]
CurveName: TypeAlias = Literal[
    "curve25519",
    "p256",
    "p384",
    "p521",
    "brainpoolp256r1",
    "brainpoolp384r1",
    "brainpoolp512r1",
    "secp256k1",
]
DsaKeySizeBits: TypeAlias = Literal[1024, 2048, 3072]
KeyVersionNumber: TypeAlias = Literal[4, 6]
AeadPreference: TypeAlias = Tuple[SymmetricAlgorithmName, AeadAlgorithmName]


class EncryptionCaps:
    @staticmethod
    def none() -> EncryptionCaps: ...
    @staticmethod
    def communication() -> EncryptionCaps: ...
    @staticmethod
    def storage() -> EncryptionCaps: ...
    @staticmethod
    def all() -> EncryptionCaps: ...


class KeyType:
    @staticmethod
    def rsa(bits: int) -> KeyType: ...
    @staticmethod
    def dsa(bits: DsaKeySizeBits) -> KeyType: ...
    @staticmethod
    def ed25519_legacy() -> KeyType: ...
    @staticmethod
    def ed25519() -> KeyType: ...
    @staticmethod
    def ed448() -> KeyType: ...
    @staticmethod
    def ecdsa(curve: CurveName) -> KeyType: ...
    @staticmethod
    def ecdh(curve: CurveName) -> KeyType: ...
    @staticmethod
    def x25519() -> KeyType: ...
    @staticmethod
    def x448() -> KeyType: ...
    def can_sign(self) -> bool: ...
    def can_encrypt(self) -> bool: ...


class SubkeyParams:
    pass


class SubkeyParamsBuilder:
    def __init__(self) -> None: ...
    def version(self, value: KeyVersionNumber) -> SubkeyParamsBuilder: ...
    def key_type(self, value: KeyType) -> SubkeyParamsBuilder: ...
    def can_sign(self, value: bool) -> SubkeyParamsBuilder: ...
    def can_encrypt(self, value: EncryptionCaps) -> SubkeyParamsBuilder: ...
    def can_authenticate(self, value: bool) -> SubkeyParamsBuilder: ...
    def created_at(self, value: int) -> SubkeyParamsBuilder: ...
    def passphrase(self, value: Optional[str]) -> SubkeyParamsBuilder: ...
    def build(self) -> SubkeyParams: ...


class SecretKeyParams:
    def generate(self) -> SecretKey: ...


class SecretKeyParamsBuilder:
    def __init__(self) -> None: ...
    def version(self, value: KeyVersionNumber) -> SecretKeyParamsBuilder: ...
    def key_type(self, value: KeyType) -> SecretKeyParamsBuilder: ...
    def can_sign(self, value: bool) -> SecretKeyParamsBuilder: ...
    def can_certify(self, value: bool) -> SecretKeyParamsBuilder: ...
    def can_encrypt(self, value: EncryptionCaps) -> SecretKeyParamsBuilder: ...
    def can_authenticate(self, value: bool) -> SecretKeyParamsBuilder: ...
    def created_at(self, value: int) -> SecretKeyParamsBuilder: ...
    def feature_seipd_v1(self, value: bool) -> SecretKeyParamsBuilder: ...
    def feature_seipd_v2(self, value: bool) -> SecretKeyParamsBuilder: ...
    def preferred_symmetric_algorithms(
        self, values: List[SymmetricAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_hash_algorithms(
        self, values: List[HashAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_compression_algorithms(
        self, values: List[CompressionAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_aead_algorithms(
        self, values: List[AeadPreference]
    ) -> SecretKeyParamsBuilder: ...
    def passphrase(self, value: Optional[str]) -> SecretKeyParamsBuilder: ...
    def primary_user_id(self, value: str) -> SecretKeyParamsBuilder: ...
    def user_id(self, value: str) -> SecretKeyParamsBuilder: ...
    def user_ids(self, values: List[str]) -> SecretKeyParamsBuilder: ...
    def subkey(self, value: SubkeyParams) -> SecretKeyParamsBuilder: ...
    def build(self) -> SecretKeyParams: ...
    def generate(self) -> SecretKey: ...


class PublicKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[PublicKey, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> PublicKey: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def user_ids(self) -> List[str]: ...
    def verify_bindings(self) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...


class SecretKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[SecretKey, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> SecretKey: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def secret_subkey_count(self) -> int: ...
    @property
    def user_ids(self) -> List[str]: ...
    def verify_bindings(self) -> None: ...
    def to_public_key(self) -> PublicKey: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...


class SignatureInfo:
    @property
    def version(self) -> int: ...
    @property
    def signature_type(self) -> Optional[str]: ...
    @property
    def hash_algorithm(self) -> Optional[str]: ...
    @property
    def public_key_algorithm(self) -> Optional[str]: ...
    @property
    def issuer_key_ids(self) -> List[str]: ...
    @property
    def issuer_fingerprints(self) -> List[str]: ...
    @property
    def creation_time(self) -> Optional[int]: ...
    @property
    def signature_expiration_seconds(self) -> Optional[int]: ...
    @property
    def signer_user_id(self) -> Optional[str]: ...
    @property
    def signed_hash_value(self) -> Optional[bytes]: ...
    @property
    def salt(self) -> Optional[bytes]: ...
    @property
    def is_one_pass(self) -> bool: ...


class Message:
    @staticmethod
    def from_armor(data: str) -> Tuple[Message, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> Message: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def headers(self) -> Optional[Headers]: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def payload_bytes(self) -> bytes: ...
    def payload_text(self) -> str: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...
    def signature_count(self) -> int: ...
    def one_pass_signature_count(self) -> int: ...
    def regular_signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def verify_signature(self, key: PublicKey, index: int = 0) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: int = 0) -> None: ...
    def decrypt(
        self, key: SecretKey, password: Optional[str] = None
    ) -> DecryptedMessage: ...
    def decrypt_with_password(self, password: str) -> DecryptedMessage: ...


class DecryptedMessage:
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def payload_bytes(self) -> bytes: ...
    def payload_text(self) -> str: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...
    def signature_count(self) -> int: ...
    def one_pass_signature_count(self) -> int: ...
    def regular_signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def verify_signature(self, key: PublicKey, index: int = 0) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: int = 0) -> None: ...


class DetachedSignature:
    @staticmethod
    def from_armor(data: str) -> Tuple[DetachedSignature, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> DetachedSignature: ...
    @staticmethod
    def sign_binary(
        data: bytes, key: SecretKey, password: Optional[str] = None
    ) -> DetachedSignature: ...
    def signature_info(self) -> SignatureInfo: ...
    def verify(self, key: PublicKey, data: bytes) -> None: ...
    def verify_signature(self, key: PublicKey, data: bytes) -> SignatureInfo: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...


class CleartextSignedMessage:
    @staticmethod
    def from_armor(data: str) -> Tuple[CleartextSignedMessage, Headers]: ...
    @staticmethod
    def sign(
        text: str, key: SecretKey, password: Optional[str] = None
    ) -> CleartextSignedMessage: ...
    @property
    def text(self) -> str: ...
    def signed_text(self) -> str: ...
    def signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def verify_signature(
        self, key: PublicKey, index: Optional[int] = None
    ) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: Optional[int] = None) -> None: ...
    def to_armored(self) -> str: ...


class MessageInfo:
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def headers(self) -> Optional[Headers]: ...


def inspect_message(data: str) -> MessageInfo: ...
def inspect_message_bytes(data: bytes) -> MessageInfo: ...
def sign_message(
    data: bytes, signer: SecretKey, password: Optional[str] = None, file_name: str = ""
) -> str: ...
def sign_cleartext_message(
    text: str, signer: SecretKey, password: Optional[str] = None
) -> str: ...
def encrypt_message_to_recipient(
    data: bytes,
    recipient: PublicKey,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
) -> str: ...
def encrypt_message_with_password(
    data: bytes,
    password: str,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
) -> str: ...
